In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("cars.csv")
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [3]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   body-style         205 non-null    object
 5   drive-wheels       205 non-null    object
 6   engine-location    205 non-null    object
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    object
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB

In [5]:
df['normalized-losses'].replace('?',np.nan,inplace=True)
df['normalized-losses']=df['normalized-losses'].astype("float")
df['normalized-losses'].fillna(df['normalized-losses'].mean(),inplace=True)

df['horsepower'].replace('?',np.nan,inplace=True)
df['horsepower']=df['horsepower'].astype("float")
df['horsepower'].fillna(df['horsepower'].mean(),inplace=True)

In [6]:
x=df.iloc[:,:-1]
y=df['price']

In [7]:
x

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg
0,3,122.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27
1,3,122.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27
2,1,122.0,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,23,28
201,-1,95.0,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160.0,19,25
202,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134.0,18,23
203,-1,95.0,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106.0,26,27
204,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,19,25

In [24]:
num_feature=x.select_dtypes(['int64','float64'])
cat_feature=x.select_dtypes(object).columns

In [25]:
num_feature

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,0.0,1.0,0.0,2.0,0.0,0.0
1,3,122.0,64.1,48.8,130,111.0,21,27,0.0,1.0,0.0,2.0,0.0,0.0
2,1,122.0,65.5,52.4,152,154.0,19,26,0.0,1.0,2.0,2.0,0.0,5.0
3,2,164.0,66.2,54.3,109,102.0,24,30,1.0,1.0,3.0,1.0,0.0,3.0
4,2,164.0,66.4,54.3,136,115.0,18,22,1.0,1.0,3.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,68.9,55.5,141,114.0,23,28,21.0,1.0,3.0,2.0,0.0,3.0
201,-1,95.0,68.8,55.5,141,160.0,19,25,21.0,1.0,3.0,2.0,0.0,3.0
202,-1,95.0,68.9,55.5,173,134.0,18,23,21.0,1.0,3.0,2.0,0.0,5.0
203,-1,95.0,68.9,55.5,145,106.0,26,27,21.0,0.0,3.0,2.0,0.0,3.0
204,-1,95.0,68.9,55.5,141,114.0,19,25,21.0,1.0,3.0,2.0,0.0,3.0

In [10]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
x[cat_feature]=oe.fit_transform(x[cat_feature])

In [26]:
x[cat_feature]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[205 rows x 0 columns]

In [13]:
x

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,0.0,1.0,0.0,2.0,0.0,0.0
1,3,122.0,64.1,48.8,130,111.0,21,27,0.0,1.0,0.0,2.0,0.0,0.0
2,1,122.0,65.5,52.4,152,154.0,19,26,0.0,1.0,2.0,2.0,0.0,5.0
3,2,164.0,66.2,54.3,109,102.0,24,30,1.0,1.0,3.0,1.0,0.0,3.0
4,2,164.0,66.4,54.3,136,115.0,18,22,1.0,1.0,3.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,68.9,55.5,141,114.0,23,28,21.0,1.0,3.0,2.0,0.0,3.0
201,-1,95.0,68.8,55.5,141,160.0,19,25,21.0,1.0,3.0,2.0,0.0,3.0
202,-1,95.0,68.9,55.5,173,134.0,18,23,21.0,1.0,3.0,2.0,0.0,5.0
203,-1,95.0,68.9,55.5,145,106.0,26,27,21.0,0.0,3.0,2.0,0.0,3.0
204,-1,95.0,68.9,55.5,141,114.0,19,25,21.0,1.0,3.0,2.0,0.0,3.0

In [27]:
from sklearn.model_selection import train_test_split
xtrain,xtest,xytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=1)

In [15]:
from sklearn.linear_model import LinearRegression
lreg=LinearRegression
lreg.fit(xtrain,ytrain)
ypred=lreg.predict(xtest)

In [16]:
train=lreg.score(xtrain,ytrain) #training accuracy
test=lreg.score(xtest,ytest)    #testing accuracy
print(f"training result: {train}")
print(f"testing result: {test}")

training result: 0.8504573774895474
testing result: 0.7965566780397383

High traing score and low testing score
means low traing error ie low bias 
and high test error ie high variance
so it is overfitting model
so we need regularization

In [17]:
from sklearn.linear_model import Ridge,Lasso

In [18]:
l2=Ridge(alpha=5)
#alpha value imporves quality of data and reduce variance
l2.fit(xtrain,ytrain)

Ridge(alpha=5)

In [19]:
train=l2.score(xtrain,ytrain) #training accuracy
test=l2.score(xtest,ytest)    #testing accuracy
print(f"training result: {train}")
print(f"testing result: {test}")

training result: 0.8214255248858178
testing result: 0.8141745853539418

In [20]:
#hypertuning of alpha/lambda value
for i in range(1,31):
    l2=Ridge(alpha=i)
    l2.fit(xtrain,ytrain)
    test=l2.score(xtest,ytest)
    print(f"Value of alpha: {i}, Test score: {test}")

Value of alpha: 1, Test score: 0.8074518758147271
Value of alpha: 2, Test score: 0.8110292248150516
Value of alpha: 3, Test score: 0.8126933383890032
Value of alpha: 4, Test score: 0.81361486450293
Value of alpha: 5, Test score: 0.8141745853539418
Value of alpha: 6, Test score: 0.8145301242133357
Value of alpha: 7, Test score: 0.8147582608502812
Value of alpha: 8, Test score: 0.8149010602831951
Value of alpha: 9, Test score: 0.8149836949253052
Value of alpha: 10, Test score: 0.815022286737653
Value of alpha: 11, Test score: 0.8150277245431792
Value of alpha: 12, Test score: 0.8150076788279418
Value of alpha: 13, Test score: 0.8149677381788262
Value of alpha: 14, Test score: 0.8149120868051177
Value of alpha: 15, Test score: 0.814843927825252
Value of alpha: 16, Test score: 0.8147657584947391
Value of alpha: 17, Test score: 0.8146795554128126
Value of alpha: 18, Test score: 0.8145869029046836
Value of alpha: 19, Test score: 0.8144890843369587
Value of alpha: 20, Test score: 0.8143871485445551
Value of alpha: 21, Test score: 0.8142819591129826
Value of alpha: 22, Test score: 0.8141742315788496
Value of alpha: 23, Test score: 0.814064561942154
Value of alpha: 24, Test score: 0.8139534488166063
Value of alpha: 25, Test score: 0.8138413108452037
Value of alpha: 26, Test score: 0.8137285005403767
Value of alpha: 27, Test score: 0.8136153153884842
Value of alpha: 28, Test score: 0.8135020068362638
Value of alpha: 29, Test score: 0.813388787619721
Value of alpha: 30, Test score: 0.8132758377831446

In [21]:
#final l2 model with best aplha value ie global minima or sweet point
l2=Ridge(alpha=11)
l2.fit(xtrain,ytrain)
train=l2.score(xtrain,ytrain) 
test=l2.score(xtest,ytest)    
print(f"training result: {train}")
print(f"testing result: {test}")

training result: 0.8096241695970485
testing result: 0.8150277245431792

L1 regularizaton is lasso:Least absolute and selection operator

In [22]:
for i in range(201,250):
    l1=Lasso(alpha=i)
    l1.fit(xtrain,ytrain)
    test=l1.score(xtest,ytest)
    print(f"Value of alpha: {i}, Test score: {test}")

Value of alpha: 201, Test score: 0.8139280662762406
Value of alpha: 202, Test score: 0.8139351596604211
Value of alpha: 203, Test score: 0.8139414452413292
Value of alpha: 204, Test score: 0.8139468631678923
Value of alpha: 205, Test score: 0.8139514440169054
Value of alpha: 206, Test score: 0.813955187854152
Value of alpha: 207, Test score: 0.8139580947656483
Value of alpha: 208, Test score: 0.8139601648600467
Value of alpha: 209, Test score: 0.8139614191109493
Value of alpha: 210, Test score: 0.8139618129219519
Value of alpha: 211, Test score: 0.8139613886609691
Value of alpha: 212, Test score: 0.8139601251073795
Value of alpha: 213, Test score: 0.8139580067110748
Value of alpha: 214, Test score: 0.8139550662926407
Value of alpha: 215, Test score: 0.8139512871144872
Value of alpha: 216, Test score: 0.813946668543856
Value of alpha: 217, Test score: 0.8139412205900793
Value of alpha: 218, Test score: 0.8139349321776368
Value of alpha: 219, Test score: 0.8139278044131175
Value of alpha: 220, Test score: 0.8139198412531332
Value of alpha: 221, Test score: 0.8139110395684611
Value of alpha: 222, Test score: 0.8139013960835559
Value of alpha: 223, Test score: 0.8138907327491184
Value of alpha: 224, Test score: 0.8138793495175789
Value of alpha: 225, Test score: 0.8138679413173149
Value of alpha: 226, Test score: 0.8138517841273681
Value of alpha: 227, Test score: 0.8138300965530065
Value of alpha: 228, Test score: 0.813808862026844
Value of alpha: 229, Test score: 0.8137720953012534
Value of alpha: 230, Test score: 0.813711245411585
Value of alpha: 231, Test score: 0.8136506073167215
Value of alpha: 232, Test score: 0.8135895879419386
Value of alpha: 233, Test score: 0.813528129292549
Value of alpha: 234, Test score: 0.8134662345475686
Value of alpha: 235, Test score: 0.813403946937606
Value of alpha: 236, Test score: 0.8133412664626607
Value of alpha: 237, Test score: 0.8132781990167931
Value of alpha: 238, Test score: 0.8132147054024553
Value of alpha: 239, Test score: 0.8131507954227815
Value of alpha: 240, Test score: 0.8130864923620045
Value of alpha: 241, Test score: 0.8130217962201243
Value of alpha: 242, Test score: 0.8129567069971414
Value of alpha: 243, Test score: 0.8128913288695013
Value of alpha: 244, Test score: 0.8128254778583943
Value of alpha: 245, Test score: 0.8127592338606417
Value of alpha: 246, Test score: 0.8126926014737257
Value of alpha: 247, Test score: 0.8126255181986869
Value of alpha: 248, Test score: 0.8125580417077236
Value of alpha: 249, Test score: 0.8124901720008357

In [23]:
#best alpha value final lasso model
l1=Lasso(alpha=210)
l1.fit(xtrain,ytrain)
train=l1.score(xtrain,ytrain) 
test=l1.score(xtest,ytest)    
print(f"training result: {train}")
print(f"testing result: {test}")

training result: 0.7934745679064638
testing result: 0.8139618129219519